import kleur from "kleur"
import { join } from "path"
import { existsSync, chmodSync, writeFileSync } from "fs"
import { allAdapters } from "../adapters"
import { forceRelink, removeRedundantGeminiSkillsSymlink } from "../utils/symlink"
import { getChainHome } from "../utils/chain-home"
import { ensureCoreAssets, ensureUserRegistry } from "../utils/core-assets"

export async function runSetup(opts: { ide?: string } = {}): Promise<void> {
  const chainHome = getChainHome()
  const repoRoot = chainHome

  console.log(kleur.bold("\n🔗 chain setup (V2)"))
  console.log(kleur.dim("   Source: " + chainHome + "\n"))

  ensureCoreAssets({ chainHome })
  ensureUserRegistry({ chainHome })

  const hookPath = join(repoRoot, ".git", "hooks", "pre-commit")
  if (existsSync(join(repoRoot, ".git"))) {
    const hookContent = [
      "#!/bin/bash",
      "# Autogenerated by chain CLI (V2)",
      'REPO_ROOT="$(git rev-parse --show-toplevel)"',
      'if [ ! -f "$REPO_ROOT/skills-registry.yaml" ]; then',
      '  echo "chain: skills-registry.yaml not found — skipping validation (run \'chain init\' to initialize)"',
      "  exit 0",
      "fi",
      'cd "$REPO_ROOT/cli" && CHAIN_HOME="$REPO_ROOT" bun run chain.ts validate',
      "",
    ].join("\n")
    writeFileSync(hookPath, hookContent, "utf-8")
    chmodSync(hookPath, "755")
    console.log(kleur.green("  ✓ Pre-commit hook updated"))
  }

  const adapters = allAdapters.filter((a) => {
    if (opts.ide) return a.name.toLowerCase().includes(opts.ide.toLowerCase())
    return a.detect()
  })

  if (adapters.length === 0) {
    console.log(kleur.yellow("\n  No supported IDEs detected."))
  } else {
    for (const adapter of adapters) {
      console.log(kleur.bold("\n  " + adapter.name))
      if (adapter.infoUrl) {
        console.log(kleur.dim("    " + adapter.infoUrl))
      }
      for (const link of adapter.links(chainHome)) {
        try {
          const result = forceRelink(link.from, link.to)
          console.log(kleur.green("    " + link.description + " (" + result + ")"))
        } catch (err) {
          console.error(kleur.red("    ❌ Failed to link " + link.description))
        }
      }
    }
  }

  if (removeRedundantGeminiSkillsSymlink(chainHome)) {
    console.log(
      kleur.cyan(
        "  ℹ Removed redundant ~/.gemini/skills symlink (skills load from ~/.agents/skills for Gemini CLI).",
      ),
    )
  }

  console.log(kleur.green("\n  ✓ Setup complete! Chain Hub is synchronized.\n"))
}
